# [===========================Hepoko:Control===================================================]

# [===Основное===]
enabled-ban: true
enabled-mute: true
enabled-report: true

broadcast: true       # Глобальное объявление от администрации [&c цвета поддерживаются]


# [===Дополнительно===]

# Системные баны (Модуль СУБД блокировок)
ban:
  tempban: true         # Временный бан игрока по никнейму
  tempban-ip: true      # Временный бан игрока или IP-адреса
  unban: true           # Снятие бана с никнейма
  unban-ip: true        # Снятие бана с IP-адреса
  banlist: true         # Просмотр списка активных забаненных игроков
  banlist-ip: true      # Просмотр списка активных забаненных IP
  baninfo: true         # Просмотр подробной карточки бана

# Ограничения чата (Модуль мутов)
mute:
  tempmute: true        # Временный мут игрока в чате
  unmute: true          # Снятие мута с игрока

# Модуль жалоб (Репорты и GUI меню)
report:
  report: true          # Возможность для игроков отправить жалобу администраторам
  reportlist: true      # Графическое GUI-меню с головами для модерации жалоб