# [======================================Global:Hepoko====================================================]

AuthEveryDay: true
Control: true
CustomChat: true
MimicChest: false
TabManager: true
CoreProtect: true

debug: false
