# [========================================Hepoko:MimikChest=====================================================]

# Шанс того, что случайно сгенерированный (или природный) сундук окажется мимиком
# Значение от 0.0 (0%) до 1.0 (100%). По умолчанию: 0.40 (40%)
chance: 0.40

# Сколько успешных кликов по буквам должен сделать игрок для победы
clicks_required: 15

# Ограничение по времени на прохождение мини-игры (в секундах)
time_limit_seconds: 15

# Количество чистого урона (в единицах HP), которое получит игрок в случае проигрыша
# Наносится напрямую по здоровью, полностью игнорируя любую броню и чары защиты.
# 2.0 HP = 1 сердце. По умолчанию: 7.0 HP (3.5 сердца)
damage_amount: 7.0

# === НАСТРОЙКИ РЕЖИМА ПРОХОЖДЕНИЯ ===
# Вы можете включить один из режимов или сразу оба (тогда типы кнопок будут перемешиваться)
mouse_click: true          # Включить QTE-клики мышкой (ЛКМ/ПКМ)
keyboard_click: true       # Включить QTE-клики клавиатурой (W, A, S, D, ПРОБЕЛ)
